mysql:
  dialect: mysql
  dsn: root:root@tcp(localhost:3309)/bpjs?charset=utf8mb4&parseTime=True&loc=Local

rabbit:
  dialect: rabbit
  dsn: amqp://guest:guest@localhost:5672

redis:
  addr: localhost:6379
  db: 10

server:
  host: 127.0.0.1
  port: 8000
